apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nem-client.fullname" . }}
  labels:
    {{- include "nem-client.labels" . | nindent 4 }}
data:
  configuser.properties: |
    {{- range $key, $value := .Values.config.user}}
    {{- if $value}}
    {{ $key }}={{ $value }}
    {{- end }}
    {{- end }}
  {{- if .Values.config.logalphaProperties }}
  logalpha.properties: |-
    {{ .Values.config.logalphaProperties | nindent 4}}
  {{- end }}
  {{- if .Values.config.dbProperties }}
  db.properties: |-
    {{ .Values.config.dbProperties | nindent 4}}
  {{- end }}
  {{- if .Values.config.peersConfigJson }}
  {{ include "peers.json.filename" . | nindent 2}}: |-
    {{ .Values.config.peersConfigJson | nindent 4}}
  {{- end }}
binaryData:
  {{ if .Values.config.customNemesisFileBase64 }}
  nemesis-file: {{ .Values.config.customNemesisFileBase64 }}
  {{- end }}
