apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nem-client.fullname" . }}
  labels:
    {{- include "nem-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nem-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nem-client.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nem-client.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: https
              containerPort: {{ .Values.service.httpsPort }}
              protocol: TCP
            - name: websocket
              containerPort: {{ .Values.service.wsPort }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /usersettings/config.properties
            name: "config"
            subPath: "configuser.properties"
          {{- if .Values.config.user.customNemesisFileBase64 }}
          - mountPath: /usersettings/nemesis.bin
            name: "config"
            subPath: "nemesis-file"
          {{- end }}
          {{- if .Values.config.peersConfigJson }}
          - mountPath: /usersettings/{{ include "peers.json.filename" .}}
            name: "config"
            subPath: {{ include "peers.json.filename" .}}
          {{- end }}
          {{- if .Values.config.dbProperties }}
          - mountPath: /usersettings/db.properties
            name: "config"
            subPath: "db.properties"
          {{- end }}
          - mountPath: /home/nem/nem
            name: "nem-data"
            subPath: "nem"
      volumes:
      - name: config
        configMap:
          name: config-map
          items:
          - key: "configuser.properties"
            path: "configuser.properties"
          {{- if .Values.config.user.customNemesisFileBase64 }}
          - key: "nemesis-file"
            path: "nemesis-file"
          {{- end }}
          {{- if .Values.config.peersConfigJson }}
          - key: {{ include "peers.json.filename" . | quote}}
            path: {{ include "peers.json.filename" . | quote}}
          {{- end }}
          {{- if .Values.config.dbProperties }}
          - key: "db.properties"
            path: "db.properties"
          {{- end }}
      - name: nem-data
        persistentVolumeClaim:
          claimName: nem-pv-claim
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
