apiVersion: v1
kind: PersistentVolume
metadata:
  name: nem-pv
  annotations:
    "helm.sh/resource-policy": keep
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/k8s-pvs/nem-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ required "A valid .Values.clusterName is required!" .Values.clusterName }}
