apiVersion: v1
kind: Service
metadata:
  name: {{ include "nem-client.fullname" . }}
  labels:
    {{- include "nem-client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  allocateLoadBalancerNodePorts: false
  {{- end }}
  ports:
    - port: {{ index .Values.config.user "nem.httpPort" }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ index .Values.config.user "nem.httpPort" }}
      {{- end }}
      protocol: TCP
      name: http
    - port: {{ index .Values.config.user "nem.httpsPort" }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ index .Values.config.user "nem.httpsPort" }}
      {{- end }}
      protocol: TCP
      name: https
    - port: {{ index .Values.config.user "nem.websocketPort" }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ index .Values.config.user "nem.websocketPort" }}
      {{- end }}
      protocol: TCP
      name: websocket
  selector:
    {{- include "nem-client.selectorLabels" . | nindent 4 }}
