# Default values for nem-client.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Overrides the chart's name
nameOverride: ""

# -- Overrides the chart's computed fullname
fullnameOverride: ""

image:
  # -- nis-client image repository
  repository: nemofficial/nis-client
  # -- nis-client image tag
  tag: "0.6.100@sha256:8ccfdb5de8cfce01c91c599fe2c91ddafe74940923e3d1bda667137747dd7dcd"
  # -- nis-client image pull policy
  pullPolicy: IfNotPresent

# -- Image pull secrets for Docker images
imagePullSecrets: []

# -- Config object for nis properties files
# @default -- See `values.yaml`
config:
  # -- config-user.properties
  # @default -- See `values.yaml`
  user:
    # -- folder database and log files should be located
    nem.folder: /app/data
    # -- mainnet|testnet
    nem.network: mainnet
    # -- api/peer http port
    nem.httpPort: 7890
    # -- api/peer https port
    nem.httpsPort: 7891
    # -- api/peer websocket port
    nem.websocketPort: 7778
    # -- hostname/ip e.g. example.com
    nem.host: 127.0.0.1
    # -- nemesis.bin file path, leave empty when no custom nemesis files, set to /usersettings/nemesis.bin otherwise
    nem.network.nemesisFilePath:
    # -- main account private key
    # @default new account will be generated and set
    nis.bootKey:
    # -- name of the NIS node
    nis.bootName:
  # -- base64 encoded nemesis.bin file content
  customNemesisFileBase64:
  # config.logalphaProperties -- (string) nis-client logalpha.properties file content as multi-line string
  logalphaProperties:
  # config.dbProperties -- (string) nis-client db.properties file content as multi-line string
  dbProperties:
  # config.peersConfigJson -- (string) nis-client peers-config.json file content as multi-line string
  peersConfigJson:


service:
  # -- Service type: ClusterIP|LoadBalancer|NodePort
  type: ClusterIP
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# -- Annotations for the StatefulSet
annotations: {}

persistence:
  # -- Uses an EmptyDir when not enabled
  enabled: true
  # -- Use an existing PVC when persistence.enabled
  existingClaim: null
  # -- Access mode for the volume claim template
  accessModes:
  - ReadWriteOnce
  # -- Requested size for volume claim template
  size: 8Gi
  # -- Use a specific storage class
  # E.g 'local-path' for local storage to achieve best performance
  # Read more (https://github.com/rancher/local-path-provisioner)
  storageClassName: local-path
  # -- Annotations for volume claim template
  annotations:
    "helm.sh/resource-policy": keep
  # -- Selector for volume claim template
  selector: {}
  #   matchLabels:
  #     app.kubernetes.io/name: something

# -- Pod annotations
podAnnotations: {}

# -- Pod management policy
podManagementPolicy: OrderedReady

# -- Pod labels
podLabels: {}

# -- The security context for pods
# @default -- See `values.yaml`
podSecurityContext:
  runAsUser: 11001
  fsGroup: 11001
  runAsGroup: 11001
  runAsNonRoot: true

# -- The security context for containers
containerSecurityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- The application is given a certain amount of time to shutdown before it's terminated forcefully
terminationGracePeriodSeconds: 300

# TODO using the rules?
rbac:
  # -- Specifies whether RBAC resources are to be created
  create: true
  # -- Required ClusterRole rules
  # @default -- See `values.yaml`
  clusterRules:
     # Required to obtain the nodes external IP
    - apiGroups: [""]
      resources:
      - "nodes"
      verbs:
      - "get"
      - "list"
      - "watch"
  # -- Required ClusterRole rules
  # @default -- See `values.yaml`
  rules:
    # Required to get information about the services nodePort.
    - apiGroups: [""]
      resources:
      - "services"
      verbs:
      - "get"
      - "list"
      - "watch"

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Liveness probe
# @default -- See `values.yaml`
livenessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 60
  periodSeconds: 120

# -- Readiness probe
# @default -- See `values.yaml`
readinessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10

# -- Update strategy for the StatefulSet
updateStrategy:
  # -- Update strategy type (RollingUpdate|OnDelete)
  type: RollingUpdate

# -- Additional init containers
initContainers: []
# - name: my-init-container
#   image: busybox:latest
#   command: ['sh', '-c', 'echo hello']

# -- Additional containers
extraContainers: []

# -- Additional volumes
extraVolumes: []

# -- Additional volume mounts
extraVolumeMounts: []

# -- Additional ports. Useful when using extraContainers or extraContainerPorts
# @default -- See `values.yaml`
extraPorts: []
  # - port: 8890
  #   protocol: TCP
  #   name: 8890-tcp
  # - port: 8891
  #   protocol: TCP
  #   name: 8891-tcp


# -- Additional ports for the main container
extraContainerPorts: []

# -- Additional env variables
extraEnv: []

initChownData:
  # -- Init container to set the correct permissions to access data directories
  enabled: true
  image:
    # -- Container repository
    repository: busybox
    # -- Container tag
    tag: "1.35.0"
    # -- Container pull policy
    pullPolicy: IfNotPresent
  # -- Resource requests and limits
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

# -- Tolerations for pods
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# -- Affinity configuration for pods
affinity: {}
